"use client";
import { useState } from "react";
import { Dices, ShieldCheck } from "lucide-react";

function key(){return crypto.randomUUID();}
export default function DicePage(){
 const [bet,setBet]=useState(10); const [target,setTarget]=useState(50); const [mode,setMode]=useState<"under"|"over">("under"); const [roll,setRoll]=useState<number|null>(null); const [status,setStatus]=useState(""); const [busy,setBusy]=useState(false);
 const chance=mode==="under"?target:100-target; const multi=Math.floor((99/chance)*10000)/10000;
 async function play(){setBusy(true);setStatus("");try{const r=await fetch("/api/games/dice/bet",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":key()},body:JSON.stringify({betUnits:Math.round(bet*100),target,mode})});const d=await r.json();if(!r.ok)throw new Error(d.error);setRoll(d.result.roll);setStatus(d.result.won?`WIN +${(d.payoutUnits/100).toFixed(2)} GC`:`LOSS -${bet.toFixed(2)} GC`);}catch(e){setStatus(e instanceof Error?e.message:"Bet failed");}finally{setBusy(false)}}
 return <div className="gamePage"><div className="gameStage diceStage"><div className="stageTop"><span className="sectionKicker">GALAXY ORIGINAL</span><div className="fairTag"><ShieldCheck size={14}/> Server verified</div></div><div className={`diceResult ${status.startsWith("WIN")?"win":""}`}><Dices size={42}/><strong>{roll===null?"--.--":roll.toFixed(2)}</strong><span>{status||"Set your target and launch the roll"}</span></div><div className="scale"><i/><i/><i/><i/><i/></div></div><div className="betPanel"><h1>Dice</h1><div className="field"><label>Bet amount</label><div className="inputRow"><input type="number" min="0.01" step="0.01" value={bet} onChange={e=>setBet(Number(e.target.value))}/><button onClick={()=>setBet(Math.max(.01,bet/2))}>½</button><button onClick={()=>setBet(bet*2)}>2×</button></div></div><div className="field"><label>Roll mode</label><div className="seg"><button className={mode==="under"?"on":""} onClick={()=>setMode("under")}>ROLL UNDER</button><button className={mode==="over"?"on":""} onClick={()=>setMode("over")}>ROLL OVER</button></div></div><div className="field"><label>Target <b>{target.toFixed(2)}</b></label><input className="range" type="range" min="2" max="98" step="0.5" value={target} onChange={e=>setTarget(Number(e.target.value))}/></div><div className="metrics"><div><span>Win chance</span><b>{chance.toFixed(2)}%</b></div><div><span>Multiplier</span><b>{multi.toFixed(4)}×</b></div><div><span>Profit on win</span><b>{(bet*multi-bet).toFixed(2)} GC</b></div></div><button className="primaryBtn wide launchBtn" onClick={play} disabled={busy}>{busy?"ROLLING…":"ROLL DICE"}</button></div></div>
}
