"use client";
import { useMemo, useState } from "react";
import { Gem, Bomb, ShieldCheck } from "lucide-react";

type Status="IDLE"|"ACTIVE"|"LOST"|"CASHED_OUT";
export default function MinesPage(){
 const [bet,setBet]=useState(10),[mines,setMines]=useState(3),[sessionId,setSessionId]=useState(""),[selected,setSelected]=useState<number[]>([]),[revealedMines,setRevealedMines]=useState<number[]>([]),[multi,setMulti]=useState(1),[status,setStatus]=useState<Status>("IDLE"),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const selectedSet=useMemo(()=>new Set(selected),[selected]); const mineSet=useMemo(()=>new Set(revealedMines),[revealedMines]);
 async function start(){setBusy(true);setMessage("");try{const r=await fetch("/api/games/mines/start",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({betUnits:Math.round(bet*100),mines})});const d=await r.json();if(!r.ok)throw new Error(d.error);setSessionId(d.sessionId);setSelected([]);setRevealedMines([]);setMulti(1);setStatus("ACTIVE");}catch(e){setMessage(e instanceof Error?e.message:"Could not start");}finally{setBusy(false)}}
 async function pick(tile:number){if(status!=="ACTIVE"||busy||selectedSet.has(tile))return;setBusy(true);try{const r=await fetch("/api/games/mines/select",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({sessionId,tile})});const d=await r.json();if(!r.ok)throw new Error(d.error);setSelected(d.selected||selected);setMulti(d.multiplier||multi);if(d.hit){setStatus("LOST");setRevealedMines(d.mines||[]);setMessage("SUPERNOVA HIT");}else setMessage(`Safe sector · ${Number(d.multiplier).toFixed(2)}×`);}catch(e){setMessage(e instanceof Error?e.message:"Selection failed");}finally{setBusy(false)}}
 async function cashout(){if(status!=="ACTIVE")return;setBusy(true);try{const r=await fetch("/api/games/mines/cashout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({sessionId})});const d=await r.json();if(!r.ok)throw new Error(d.error);setStatus("CASHED_OUT");setRevealedMines(d.mines||[]);setMessage(`CASHED OUT +${(d.payoutUnits/100).toFixed(2)} GC`);}catch(e){setMessage(e instanceof Error?e.message:"Cashout failed");}finally{setBusy(false)}}
 return <div className="gamePage"><div className="gameStage minesStage"><div className="stageTop"><span className="sectionKicker">ASTEROID MINING</span><div className="fairTag"><ShieldCheck size={14}/> Hidden server field</div></div><div className="mineBoard">{Array.from({length:25},(_,tile)=>{const hit=mineSet.has(tile);const safe=selectedSet.has(tile)&&!hit;return <button key={tile} disabled={status!=="ACTIVE"||busy||safe} onClick={()=>pick(tile)} className={`${safe?"safe":""} ${hit?"mine":""}`}>{hit?<Bomb/>:safe?<Gem/>:<span>✦</span>}</button>})}</div><div className="mineStatus"><strong>{multi.toFixed(2)}×</strong><span>{message||"Choose a sector. Cash out before you hit a supernova."}</span></div></div><div className="betPanel"><span className="sectionKicker">GALAXY ORIGINAL</span><h1>Mines</h1><div className="field"><label>Bet amount</label><div className="inputRow"><input type="number" min="0.01" step="0.01" value={bet} disabled={status==="ACTIVE"} onChange={e=>setBet(Number(e.target.value))}/><button disabled={status==="ACTIVE"} onClick={()=>setBet(Math.max(.01,bet/2))}>½</button><button disabled={status==="ACTIVE"} onClick={()=>setBet(bet*2)}>2×</button></div></div><div className="field"><label>Mines <b>{mines}</b></label><input className="range" type="range" min="1" max="24" value={mines} disabled={status==="ACTIVE"} onChange={e=>setMines(Number(e.target.value))}/></div><div className="metrics"><div><span>Safe picks</span><b>{selected.length}</b></div><div><span>Current multiplier</span><b>{multi.toFixed(4)}×</b></div><div><span>Potential payout</span><b>{(bet*multi).toFixed(2)} GC</b></div></div>{status==="ACTIVE"?<button className="primaryBtn wide launchBtn cashoutBtn" disabled={busy||selected.length<1} onClick={cashout}>CASH OUT · {(bet*multi).toFixed(2)} GC</button>:<button className="primaryBtn wide launchBtn" disabled={busy} onClick={start}>{busy?"STARTING…":"START GAME"}</button>}</div></div>
}
