"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { Slider } from "@/components/ui/slider";
import { Activity, ArrowDownUp, BadgeCheck, CircleHelp, Clover, Coins, Dices, Flame, Gamepad2, Gem, Heart, History, House, Menu, MoonStar, Orbit, Search, ShieldCheck, Sparkles, Star, Trophy, UserRound, Volume2, VolumeX, X, Zap } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import type { GameId } from "@/lib/galaxy/games";
import "./casino.css";
import FairVerifier from "./fair-verifier";
import { useAuth } from "./AuthProvider";
import { firebaseDb } from "@/lib/firebase/client";
import { onValue, ref } from "firebase/database";
import LiveActivity from "./live-activity";
import RoundLoader from "./round-loader";

type Game = { id: GameId; name: string; category: string; line: string; color: string; icon: LucideIcon; initial: string };
const games: Game[] = [
  { id:"dice",name:"Dice",category:"Classic",line:"Choose your odds",color:"violet",icon:Dices,initial:"01" },
  { id:"crash",name:"Crash",category:"Instant",line:"Reach escape velocity",color:"cyan",icon:Zap,initial:"02" },
  { id:"plinko",name:"Plinko",category:"Drop",line:"Find your orbit",color:"pink",icon:CircleHelp,initial:"03" },
  { id:"towers",name:"Towers",category:"Climb",line:"Ascend the unknown",color:"blue",icon:Trophy,initial:"04" },
  { id:"mines",name:"Mines",category:"Reveal",line:"Find the stars",color:"amber",icon:Gem,initial:"05" },
  { id:"hilo",name:"Hi-Lo",category:"Cards",line:"Read the next card",color:"green",icon:ArrowDownUp,initial:"06" },
  { id:"blackjack",name:"Blackjack",category:"Cards",line:"Beat the dealer",color:"violet",icon:Clover,initial:"07" },
  { id:"coinflip",name:"Coinflip",category:"Instant",line:"Galaxy or Nova?",color:"cyan",icon:Coins,initial:"08" },
  { id:"chicken",name:"Chicken Road",category:"Climb",line:"Cross cosmic lanes",color:"orange",icon:Flame,initial:"09" },
  { id:"limbo",name:"Limbo",category:"Instant",line:"Set your target",color:"pink",icon:Activity,initial:"10" },
  { id:"wheel",name:"Wheel",category:"Spin",line:"Let it land",color:"blue",icon:Orbit,initial:"11" },
  { id:"keno",name:"Keno",category:"Pick",line:"Five numbers. Ten draws.",color:"green",icon:Star,initial:"12" },
  { id:"roulette",name:"Roulette",category:"Table",line:"Pick a color",color:"amber",icon:CircleHelp,initial:"13" },
  { id:"baccarat",name:"Baccarat",category:"Table",line:"Player, banker or tie",color:"orange",icon:Sparkles,initial:"14" },
  { id:"poker",name:"Video Poker",category:"Cards",line:"Hold and draw",color:"violet",icon:BadgeCheck,initial:"15" },
];
const sessionGames = new Set<GameId>(["towers","mines","hilo","blackjack","chicken","poker"]);
type Bet = { id:string; game:string; stake:number; payout:number; multiplier:number; outcome:Record<string,unknown>; seedHash:string; clientSeed:string; nonce:string; status:string; at:number };
type Session = { id:string; version:number; game:GameId; state:string; stake:number; multiplier:number; step:number; [key:string]:unknown };
type AppState = { balance:number; resetAt:number; joinedAt:number; seedHash:string; clientSeed:string; bets:Bet[]; favorites:string[]; active:Session|null; excludedUntil:number; sessionStartedAt:number; ageConfirmed:boolean; signedIn:boolean; isAdmin:boolean; displayName:string };
type View = "casino"|"bets"|"favorites"|"rewards"|"fairness"|"responsible"|"support"|"account";
const menuItemsForPaths: View[] = ["casino","bets","favorites","rewards","fairness","responsible","support","account"];
const format = (units:number) => (units / 100).toLocaleString("en-US", { minimumFractionDigits:2, maximumFractionDigits:2 });
const toUnits = (value:string) => /^\d{1,6}(?:\.\d{1,2})?$/.test(value) ? Math.round(Number(value) * 100) : NaN;
const card = (number:unknown) => { if (typeof number !== "number") return "?"; const ranks=["2","3","4","5","6","7","8","9","10","J","Q","K","A"]; const suits=["♠","♥","♦","♣"]; return `${ranks[number % 13]}${suits[Math.floor(number / 13)]}`; };
const jsonRequest = async <T,>(url:string, method:string, data?:unknown, idempotency?:string):Promise<T> => {
  const response = await fetch(url,{ method, headers:{ "Content-Type":"application/json", ...(idempotency ? {"Idempotency-Key":idempotency} : {}) }, body:data === undefined ? undefined : JSON.stringify(data), cache:"no-store" });
  const body = await response.json() as {error?:string};
  if (!response.ok) throw new Error(body.error || "Request failed. Try again.");
  return body as T;
};

export default function Casino({initialGame="dice",initialView="casino"}:{initialGame?:GameId;initialView?:View}) {
  const { user, loading, logout } = useAuth();
  const [app,setApp]=useState<AppState|null>(null);
  const [error,setError]=useState("");
  const [notice,setNotice]=useState("");
  const [selected,setSelected]=useState<GameId>(initialGame);
  const [view,setView]=useState<View>(initialView);
  const [query,setQuery]=useState("");
  const [searchOpen,setSearchOpen]=useState(false);
  const [menuOpen,setMenuOpen]=useState(false);
  const [muted,setMuted]=useState(true);
  const [busy,setBusy]=useState(false);
  const [amount,setAmount]=useState("10.00");
  const [target,setTarget]=useState(50);
  const [mode,setMode]=useState<"under"|"over">("under");
  const [pick,setPick]=useState("Galaxy");
  const [risk,setRisk]=useState("medium");
  const [rows,setRows]=useState(12);
  const [mines,setMines]=useState(3);
  const [difficulty,setDifficulty]=useState("medium");
  const [numbers,setNumbers]=useState<number[]>([3,11,18,27,35]);
  const [holds,setHolds]=useState<number[]>([]);
  const [latest,setLatest]=useState<Bet|null>(null);
  const [session,setSession]=useState<Session|null>(null);
  const [revealed,setRevealed]=useState<{serverSeed:string;serverSeedHash:string;clientSeed:string;revealedAt:number}[]>([]);
  const [clientSeedInput,setClientSeedInput]=useState("");
  const [currentTime,setCurrentTime]=useState(0);

  const refresh = useCallback(async () => {
    if (!user) return;
    try { const data = await jsonRequest<AppState>("/api/state","GET"); setApp(data); if(data.active) { setSession(data.active); setSelected(data.active.game); } setError(""); }
    catch(e) { setError(e instanceof Error ? e.message : "Could not load demo wallet."); }
  },[user]);
  useEffect(()=>{ if (loading || !user) return; const initial=setTimeout(()=>{ void refresh(); setCurrentTime(Date.now()); },0); const timer=setInterval(()=>setCurrentTime(Date.now()),30000); return()=>{clearTimeout(initial);clearInterval(timer);}; },[refresh,loading,user]);
  useEffect(()=>{
    if (!user) return;
    return onValue(ref(firebaseDb,`playerViews/${user.uid}`),snapshot=>{
      const live=snapshot.val() as {balance?:number;active?:Session|null;latestBet?:Bet|null}|null;
      if (!live) return;
      setApp(previous=>previous ? {...previous,balance:typeof live.balance==="number"?live.balance:previous.balance,active:live.active??null,bets:live.latestBet && !previous.bets.some(b=>b.id===live.latestBet?.id)?[live.latestBet,...previous.bets].slice(0,24):previous.bets} : previous);
      if (live.active) { setSession(live.active); setSelected(live.active.game); }
      else setSession(previous=>previous?.state==="ACTIVE" ? null : previous);
    });
  },[user]);
  useEffect(()=>{ if("serviceWorker" in navigator) navigator.serviceWorker.register("/sw.js").catch(()=>{}); },[]);
  useEffect(()=>{ const onKey=(e:KeyboardEvent)=>{ if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k") { e.preventDefault(); setSearchOpen(v=>!v); } if(e.key==="Escape") { setSearchOpen(false); setMenuOpen(false); } }; window.addEventListener("keydown",onKey); return()=>window.removeEventListener("keydown",onKey); },[]);
  useEffect(()=>{ const onBack=()=>{ const parts=location.pathname.split("/").filter(Boolean); if(parts[0]==="games"&&games.some(g=>g.id===parts[1])) {setSelected(parts[1] as GameId);setView("casino");} else if(menuItemsForPaths.includes(parts[0] as View)) setView(parts[0] as View); else setView("casino");};window.addEventListener("popstate",onBack);return()=>window.removeEventListener("popstate",onBack);},[]);
  useEffect(()=>{
    type BrowserTool={name:string;title:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean;untrustedContentHint:boolean};execute:(input:unknown)=>Promise<unknown>};
    const context=(document as Document & {modelContext?:{registerTool:(tool:BrowserTool,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
    if(!context?.registerTool)return;
    const lifecycle=new AbortController();
    const validGame=(input:unknown):GameId=>{if(!input||typeof input!=="object"||!("game" in input)||typeof input.game!=="string"||!games.some(g=>g.id===input.game))throw new Error("Choose a Galaxy Original.");return input.game as GameId;};
    const register=(tool:BrowserTool)=>{try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{/* Browser does not support this optional interface. */}};
    register({name:"open_galaxy_game",title:"Open Galaxy Original",description:"Open a named Galaxy Bets demo game in the visible play area.",inputSchema:{type:"object",properties:{game:{type:"string",enum:games.map(g=>g.id)}},required:["game"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(input){const game=validGame(input);setSelected(game);setView("casino");window.history.pushState(null,"",`/games/${game}`);return {game,opened:true};}});
    register({name:"play_galaxy_demo_bet",title:"Play demo bet",description:"Place a demo credits bet in a Galaxy Original and show its result or active session.",inputSchema:{type:"object",properties:{game:{type:"string",enum:games.map(g=>g.id)},stakeGC:{type:"number",minimum:1,maximum:1000},options:{type:"object"}},required:["game","stakeGC"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(input){const game=validGame(input);const payload=input as {stakeGC:unknown;options?:Record<string,unknown>};const stake=Math.round(Number(payload.stakeGC)*100);if(!Number.isFinite(stake)||stake<100||stake>100000)throw new Error("Bet must be 1–1,000 GC.");const result=await jsonRequest<{balance:number;session?:Session;bet?:Bet}>(sessionGames.has(game)?"/api/session":"/api/play","POST",{game,stake,options:payload.options??{}},crypto.randomUUID());setSelected(game);setView("casino");window.history.pushState(null,"",`/games/${game}`);if(result.session)setSession(result.session);if(result.bet)setLatest(result.bet);await refresh();return {game,balanceGC:result.balance/100,betId:result.bet?.id,sessionId:result.session?.id,outcome:result.bet?.outcome??null};}});
    return()=>lifecycle.abort();
  },[refresh]);
  useEffect(()=>{ if(view==="fairness") jsonRequest<{revealed:typeof revealed}>("/api/fairness","GET").then(data=>setRevealed(data.revealed)).catch(()=>{}); },[view]);
  const game = games.find(g=>g.id===selected)!;
  const active = session?.state === "ACTIVE" ? session : null;
  const selectedSession = session?.game === selected ? session : null;
  const filtered = useMemo(()=>games.filter(g => `${g.name} ${g.category}`.toLowerCase().includes(query.toLowerCase())),[query]);
  const showNotice = (message:string)=>{ setNotice(message); setTimeout(()=>setNotice(""),4200); };
  const chooseGame=(id:GameId)=>{setSelected(id);setView("casino");setSearchOpen(false);setMenuOpen(false);setLatest(null);setPick(id==="roulette"?"red":id==="baccarat"?"player":"Galaxy");setTarget(id==="limbo"||id==="crash"?2:50);window.history.pushState(null,"",`/games/${id}`);window.scrollTo({top:0,behavior:"smooth"});};
  const navigate=(destination:View)=>{setView(destination);setMenuOpen(false);window.history.pushState(null,"",destination==="casino"?"/":`/${destination}`);window.scrollTo({top:0,behavior:"smooth"});};
  const options=()=>{
    if(selected==="dice") return { target,mode };
    if(selected==="limbo"||selected==="crash") return { target:Math.max(1.1,Math.min(100,target)) };
    if(selected==="coinflip"||selected==="roulette"||selected==="baccarat") return { pick };
    if(selected==="plinko") return { rows,risk };
    if(selected==="mines") return { mineCount:mines };
    if(selected==="towers"||selected==="chicken") return { difficulty };
    if(selected==="keno") return { selected:numbers };
    return {};
  };
  const play=async()=>{
    const stake=toUnits(amount);
    if(!Number.isInteger(stake)||stake<100||stake>100000) { showNotice("Enter a bet from 1 to 1,000 GC.");return; }
    if(app && app.excludedUntil>currentTime) { showNotice("Play is paused for your account.");return; }
    setBusy(true);setError("");setLatest(null);
    try {
      const result=await jsonRequest<{balance:number;session?:Session;bet?:Bet}>(sessionGames.has(selected)?"/api/session":"/api/play","POST",{game:selected,stake,options:options()},crypto.randomUUID());
      setApp(previous=>previous ? {...previous,balance:result.balance} : previous);
      if(result.session) {setSession(result.session);showNotice(`${game.name} started`);}
      if(result.bet) {const bet=result.bet;setLatest(bet);setApp(previous=>previous?{...previous,bets:[bet,...previous.bets].slice(0,24)}:previous);showNotice(bet.payout>0?`Won ${format(bet.payout)} GC`:`${game.name} result recorded`);}
    } catch(e) {showNotice(e instanceof Error?e.message:"Unable to play.");}
    finally {setBusy(false);}
  };
  const move=async(action:string,pickValue?:unknown)=>{
    if(!active) return;
    setBusy(true);
    try { const result=await jsonRequest<{balance:number;session:Session;event:string}>("/api/session","PATCH",{sessionId:active.id,version:active.version,action,pick:pickValue});
      setSession(result.session);setApp(previous=>previous?{...previous,balance:result.balance,active:result.session.state==="ACTIVE"?result.session:null}:previous);
      showNotice(result.event); if(result.session.state!=="ACTIVE") refresh();
    } catch(e) {showNotice(e instanceof Error?e.message:"Move failed.");} finally {setBusy(false);}
  };
  const accountAction=async(data:Record<string,unknown>)=>{setBusy(true);try { const result=await jsonRequest<{favorite?:boolean;balance?:number;excludedUntil?:number}>("/api/account","POST",data);if(data.action==="favorite") setApp(previous=>previous?{...previous,favorites:result.favorite?[...previous.favorites,String(data.game)]:previous.favorites.filter(g=>g!==data.game)}:previous); if(data.action==="reset"||data.action==="pause"||data.action==="confirm-adult") refresh();showNotice(data.action==="favorite"?result.favorite?"Added to favorites":"Removed from favorites":data.action==="pause"?"Cooling-off period started":data.action==="confirm-adult"?"Age and Terms confirmed":"Demo balance restored");}catch(e){showNotice(e instanceof Error?e.message:"Action failed.");}finally{setBusy(false);}};
  const rotate=async()=>{setBusy(true);try {const result=await jsonRequest<{seedHash:string;clientSeed:string;previous:{serverSeed:string;serverSeedHash:string;clientSeed:string}}>("/api/fairness","POST",{clientSeed:clientSeedInput||undefined});setApp(previous=>previous?{...previous,seedHash:result.seedHash,clientSeed:result.clientSeed}:previous);setRevealed(old=>[{...result.previous,revealedAt:Date.now()},...old]);setClientSeedInput("");showNotice("Seed rotated. Previous seed is now revealed.");}catch(e){showNotice(e instanceof Error?e.message:"Could not rotate seed.");}finally{setBusy(false);}};
  const favorite=(id:GameId)=>accountAction({action:"favorite",game:id});
  const menuItems:{id:View;label:string;icon:LucideIcon}[]=[{id:"casino",label:"Casino",icon:House},{id:"favorites",label:"Favorites",icon:Heart},{id:"bets",label:"My bets",icon:History},{id:"rewards",label:"Rewards",icon:Sparkles},{id:"fairness",label:"Provably fair",icon:ShieldCheck},{id:"responsible",label:"Responsible play",icon:MoonStar},{id:"support",label:"Support",icon:CircleHelp},{id:"account",label:"Account",icon:UserRound}];

  return <div className="gb-app">
    <aside className={`gb-sidebar ${menuOpen?"open":""}`}>
      <div className="gb-brand-row"><button className="gb-brand" onClick={()=>navigate("casino")} aria-label="Galaxy Bets home"><span className="gb-brand-mark"><Orbit size={25}/></span><span>GALAXY <b>BETS</b></span></button><button className="gb-close-mobile" onClick={()=>setMenuOpen(false)} aria-label="Close menu"><X size={21}/></button></div>
      <div className="gb-sidebar-label">EXPLORE</div>
      <nav className="gb-nav" aria-label="Main navigation">{menuItems.slice(0,4).map(item=><button key={item.id} className={view===item.id?"active":""} onClick={()=>navigate(item.id)}><item.icon size={19}/>{item.label}</button>)}</nav>
      <div className="gb-sidebar-label gb-more-label">ORIGINALS <span>{games.length}</span></div>
      <nav className="gb-nav gb-games-nav" aria-label="Games">{games.map(g=><button key={g.id} className={view==="casino"&&selected===g.id?"active":""} onClick={()=>chooseGame(g.id)}><g.icon size={18}/>{g.name}</button>)}</nav>
      <div className="gb-sidebar-label gb-more-label">MORE</div>
      <nav className="gb-nav" aria-label="More">{menuItems.slice(4).map(item=><button key={item.id} className={view===item.id?"active":""} onClick={()=>navigate(item.id)}><item.icon size={19}/>{item.label}</button>)}</nav>
      <div className="gb-sidebar-foot"><ShieldCheck size={19}/><div><strong>Demo play only</strong><span>Galaxy Credits have no cash value.</span></div></div>
    </aside>
    {menuOpen&&<button className="gb-overlay" onClick={()=>setMenuOpen(false)} aria-label="Close navigation"/>}
    <div className="gb-main-wrap">
      <header className="gb-header"><div className="gb-header-left"><button className="gb-menu-button" onClick={()=>setMenuOpen(true)} aria-label="Open menu"><Menu size={22}/></button><span className="gb-breadcrumb">GALAXY BETS <span>/</span> {view==="casino"?game.name:menuItems.find(m=>m.id===view)?.label}</span></div><div className="gb-header-actions"><button className="gb-search-btn" onClick={()=>setSearchOpen(true)} aria-label="Search games"><Search size={19}/><span>Search games</span><kbd>⌘ K</kbd></button><button className="gb-icon-btn gb-sound" onClick={()=>setMuted(!muted)} aria-label={muted?"Enable sound":"Mute sound"}>{muted?<VolumeX size={20}/>:<Volume2 size={20}/>}</button><div className="gb-wallet" title="Demo credits, no cash value"><span className="gb-wallet-orb"><Coins size={17}/></span><strong>{app?format(app.balance):"—"} <span>GC</span></strong><small>DEMO</small></div>{user?<button className="gb-account-btn" onClick={()=>navigate("account")} aria-label="Account"><UserRound size={19}/></button>:<Link href="/login" className="gb-header-login">Log in</Link>}</div></header>
      <main className="gb-main">
        {error&&<div className="gb-error" role="alert">{error}{user&&<Button size="sm" onClick={refresh}>Retry</Button>}</div>}
        {loading || (user&&!app&&!error) ? <div className="gb-loading-view" role="status"><RoundLoader/><span>Connecting to your Galaxy wallet…</span></div> : null}
        {view==="casino"&&<>
          <div className="gb-page-top"><div><div className="gb-eyebrow"><span className="gb-live-dot"/> GALAXY ORIGINALS <span className="gb-divider">/</span> {game.category.toUpperCase()}</div><h1>{game.name}</h1><p>{game.line}. Play with Galaxy Credits. No cash value.</p></div><button className={`gb-favorite-top ${app?.favorites.includes(game.id)?"saved":""}`} onClick={()=>favorite(game.id)} aria-label={app?.favorites.includes(game.id)?"Remove favorite":"Add favorite"}><Heart size={20} fill={app?.favorites.includes(game.id)?"currentColor":"none"}/></button></div>
          {active&&active.game!==selected&&<div className="gb-resume-notice">You have an active {games.find(g=>g.id===active.game)?.name} round. <Button variant="secondary" size="sm" onClick={()=>chooseGame(active.game)}>Resume game</Button></div>}
          <div className="gb-play-layout"><section className="gb-game-stage" aria-label={`${game.name} game`}><div className="gb-stage-head"><span><game.icon size={18}/> GALAXY ORIGINALS <span className="gb-stage-no">/ {game.initial}</span></span><span className="gb-stage-demo">● DEMO MODE</span></div><GameBoard game={game} latest={latest} session={selectedSession} busy={busy} move={move} holds={holds} setHolds={setHolds}/><div className="gb-stage-foot"><span><ShieldCheck size={16}/> Server verified result</span><span>18+ · No cash value</span></div></section>
            <section className="gb-bet-panel" aria-label="Game controls"><div className="gb-panel-top"><span>PLACE A DEMO BET</span><span className="gb-demo-chip">GC</span></div><label className="gb-label" htmlFor="gb-bet">Bet amount</label><div className="gb-amount"><input id="gb-bet" inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} aria-label="Bet amount in Galaxy Credits"/><span>GC</span></div><div className="gb-amount-actions"><button onClick={()=>setAmount(Math.max(1,Number(amount)/2).toFixed(2))}>½</button><button onClick={()=>setAmount(Math.min(1000,Number(amount)*2).toFixed(2))}>2×</button><button onClick={()=>setAmount(Math.min(1000,(app?.balance??0)/100).toFixed(2))}>Max</button></div><div className="gb-panel-divider"/><GameOptions game={selected} target={target} setTarget={setTarget} mode={mode} setMode={setMode} pick={pick} setPick={setPick} risk={risk} setRisk={setRisk} rows={rows} setRows={setRows} mines={mines} setMines={setMines} difficulty={difficulty} setDifficulty={setDifficulty} numbers={numbers} setNumbers={setNumbers} disabled={!!active}/><div className="gb-payout"><span>Potential payout</span><strong>{selected==="dice"?`${format(Math.floor(toUnits(amount)*.99/(mode==="under"?target/100:1-target/100)))} GC`:selected==="coinflip"?`${format(toUnits(amount)*1.98)} GC`:selectedSession?.state==="ACTIVE"?`${format(Math.floor(selectedSession.stake*selectedSession.multiplier))} GC`:"Varies by result"}</strong></div>{user&&app&&!app.ageConfirmed&&<label className="gb-consent"><input type="checkbox" checked={false} disabled={busy||!app} onChange={()=>accountAction({action:"confirm-adult"})}/><span>I confirm I am 18+ and accept the <Link href="/terms">Terms</Link>.</span></label>}<Button className="gb-play-btn" disabled={busy||!app||!app.ageConfirmed||!!active||app.excludedUntil>currentTime} onClick={play}>{busy?<><RoundLoader small/> Processing…</>:!user?"Sign in to play":!app?.ageConfirmed?"Confirm 18+ to play":active?"Finish active game":"Play demo"}{!busy&&<Sparkles size={18}/>}</Button>{!user&&<div className="gb-login-prompt"><Link href="/login">Log in</Link><span>or</span><Link href="/register">Create account</Link></div>}<p className="gb-panel-disclaimer">Demo credits only. No deposits or withdrawals.</p></section></div>
          <div className="gb-lobby-title"><div><span className="gb-eyebrow">THE COLLECTION</span><h2>Explore originals</h2></div><span>{games.length} original games</span></div><div className="gb-game-grid">{games.map(g=><div key={g.id} className={`gb-game-card ${g.color} ${g.id===selected?"current":""}`}><button className="gb-card-main" onClick={()=>chooseGame(g.id)}><div className="gb-card-art"><g.icon size={48} strokeWidth={1.25}/><span>{g.initial}</span></div><div className="gb-card-info"><span>{g.category}</span><strong>{g.name}</strong><small>{g.line}</small></div></button><button className="gb-card-heart" aria-label={`Favorite ${g.name}`} onClick={()=>favorite(g.id)}><Heart size={18} fill={app?.favorites.includes(g.id)?"currentColor":"none"}/></button></div>)}</div>
          <LiveActivity/><div className="gb-section-banner"><div><span className="gb-eyebrow">PLAY WITH INTENTION</span><h3>Stay in your orbit.</h3><p>Set a break whenever you need one. Play is always with demo credits.</p></div><Button variant="secondary" onClick={()=>navigate("responsible")}>Responsible play</Button></div>
        </>}
        {view==="bets"&&<div className="gb-content-page"><span className="gb-eyebrow">YOUR ACTIVITY</span><h1>My bets</h1><p>Every demo wager and payout is recorded on the server.</p><div className="gb-table-wrap"><table className="gb-table"><thead><tr><th>Game</th><th>Bet</th><th>Multiplier</th><th>Payout</th><th>Time</th></tr></thead><tbody>{app?.bets.map(b=><tr key={b.id}><td>{games.find(g=>g.id===b.game)?.name??b.game}<small>{b.id.slice(0,8)}</small></td><td>{format(b.stake)} GC</td><td>{b.multiplier.toFixed(2)}×</td><td className={b.payout?"gb-positive":"gb-negative"}>{format(b.payout)} GC</td><td>{new Date(b.at).toLocaleString()}</td></tr>)}</tbody></table>{!app?.bets.length&&<div className="gb-empty"><History size={28}/><strong>No bets yet</strong><Button onClick={()=>navigate("casino")}>Explore games</Button></div>}</div></div>}
        {view==="favorites"&&<div className="gb-content-page"><span className="gb-eyebrow">YOUR COLLECTION</span><h1>Favorites</h1><p>Your saved games stay with this account.</p><div className="gb-game-grid">{games.filter(g=>app?.favorites.includes(g.id)).map(g=><button key={g.id} className={`gb-game-card gb-simple-card ${g.color}`} onClick={()=>chooseGame(g.id)}><div className="gb-card-art"><g.icon size={48}/></div><div className="gb-card-info"><span>{g.category}</span><strong>{g.name}</strong></div></button>)}</div>{!app?.favorites.length&&<div className="gb-empty"><Heart size={30}/><strong>No favorites yet</strong><p>Tap a heart on any game to add it here.</p><Button onClick={()=>navigate("casino")}>Explore originals</Button></div>}</div>}
        {view==="rewards"&&<div className="gb-content-page"><span className="gb-eyebrow">DEMO REWARDS</span><h1>Refresh your credits</h1><p>Galaxy Credits have no cash value and cannot be withdrawn.</p><div className="gb-feature-card"><div className="gb-feature-icon"><Sparkles size={29}/></div><h2>10,000 GC demo refill</h2><p>Restore your demo balance once every 24 hours. Active games must finish first.</p><Button disabled={busy||!app||app.resetAt+86400000>currentTime} onClick={()=>accountAction({action:"reset"})}>Reset demo balance</Button>{!!app?.resetAt&&app.resetAt+86400000>currentTime&&<small>Available {new Date(app.resetAt+86400000).toLocaleString()}</small>}</div></div>}
        {view==="fairness"&&<div className="gb-content-page"><span className="gb-eyebrow">TRANSPARENT RESULTS</span><h1>Provably fair</h1><p>Each game uses a server seed, your client seed, and a unique nonce. The server seed hash is committed before play; rotate seeds to reveal and check the previous one.</p><div className="gb-info-grid"><div className="gb-info-card"><h2>Current commitment</h2><label>SHA-256 server seed hash</label><code>{app?.seedHash??"Loading…"}</code><label>Client seed</label><code>{app?.clientSeed??"Loading…"}</code><label htmlFor="client-seed">New client seed (optional)</label><input id="client-seed" value={clientSeedInput} onChange={e=>setClientSeedInput(e.target.value)} placeholder="Choose a seed"/><Button disabled={busy} onClick={rotate}>Rotate and reveal seed</Button></div><div className="gb-info-card"><h2>How results are generated</h2><ol><li>We publish the SHA-256 hash of a hidden server seed.</li><li>Each play uses HMAC-SHA256 with your client seed and bet nonce.</li><li>After rotation, the old seed is revealed for independent verification.</li></ol><p>Find the hash and nonce for each game in your bet record.</p></div></div><div className="gb-verifier-wrap"><FairVerifier bets={app?.bets??[]} revealed={revealed}/></div><h2 className="gb-subhead">Revealed seeds</h2>{revealed.length?revealed.map((item,i)=><div key={i} className="gb-reveal"><span>{new Date(item.revealedAt).toLocaleString()}</span><code>Seed: {item.serverSeed}</code><code>Hash: {item.serverSeedHash}</code></div>):<div className="gb-empty"><ShieldCheck size={30}/><strong>No seeds revealed yet</strong><p>Rotate your seed to reveal the previous one.</p></div>}</div>}
        {view==="responsible"&&<div className="gb-content-page"><span className="gb-eyebrow">RESPONSIBLE PLAY</span><h1>Take control of your time</h1><p>Galaxy Bets is for adults aged 18+. All credits are demo credits with no cash value.</p><div className="gb-info-grid"><div className="gb-info-card"><h2>Take a break</h2><p>A cooling-off period blocks new play on the server. It cannot be shortened.</p><div className="gb-break-buttons">{[1,24,168,720].map(hours=><Button key={hours} variant="secondary" disabled={busy||!!(app&&app.excludedUntil>currentTime)} onClick={()=>accountAction({action:"pause",hours})}>{hours===1?"1 hour":hours===24?"1 day":hours===168?"7 days":"30 days"}</Button>)}</div>{!!(app&&app.excludedUntil>currentTime)&&<p className="gb-paused">Play paused until {new Date(app.excludedUntil).toLocaleString()}.</p>}</div><div className="gb-info-card"><h2>Session awareness</h2><p>Started {app?new Date(app.sessionStartedAt).toLocaleString():"—"}. Step away any time and return later to a saved game session.</p><p>There are no payments, prizes, or cash withdrawals in demo mode.</p></div></div></div>}
        {view==="support"&&<div className="gb-content-page"><span className="gb-eyebrow">HELP CENTER</span><h1>Support</h1><p>Need help with a demo game or your account?</p><div className="gb-info-grid"><div className="gb-info-card"><h2>Game questions</h2><p>All game results are calculated on the server and stored with your bet ID. Review My bets for a record of your plays.</p><Button variant="secondary" onClick={()=>navigate("bets")}>View my bets</Button></div><div className="gb-info-card"><h2>Safety and fairness</h2><p>Review the fairness commitment, reveal old seeds, or choose a cooling-off period.</p><Button variant="secondary" onClick={()=>navigate("fairness")}>View fairness</Button></div></div></div>}
        {view==="account"&&<div className="gb-content-page"><span className="gb-eyebrow">YOUR ACCOUNT</span><h1>Player profile</h1><p>Your demo progress follows your Firebase account across devices.</p><div className="gb-profile"><div className="gb-profile-avatar"><UserRound size={34}/></div><div><strong>{app?.displayName??"Galaxy Explorer"}</strong><span>Joined {app?new Date(app.joinedAt).toLocaleDateString():"—"} · {app?.signedIn?"Signed in":"Sign in to save progress"}</span></div><span className="gb-demo-chip">DEMO</span></div><div className="gb-stats"><div><span>Balance</span><strong>{app?format(app.balance):"—"} GC</strong></div><div><span>Recent games</span><strong>{app?.bets.length??0}</strong></div><div><span>Saved favorites</span><strong>{app?.favorites.length??0}</strong></div></div><div className="gb-info-card"><h2>Account and security</h2><p>Galaxy Bets runs in demo mode. Payment methods, deposits, and withdrawals are unavailable.</p><p>Authentication is provided by Firebase. Your wager history and demo wallet are stored securely on the server.</p>{user?<Button variant="secondary" onClick={logout}>Sign out</Button>:<Link href="/login" className="gb-auth-link">Sign in to save your progress</Link>}{app?.isAdmin&&<Link href="/admin" className="gb-auth-link">Admin dashboard</Link>}</div></div>}
        <footer className="gb-footer"><span>GALAXY <b>BETS</b></span><p>Demo credits have no cash value. Adults 18+.</p><div><button onClick={()=>navigate("fairness")}>Fairness</button><button onClick={()=>navigate("responsible")}>Responsible play</button><button onClick={()=>navigate("support")}>Support</button><Link href="/terms">Terms</Link><Link href="/privacy">Privacy</Link><Link href="/cookies">Cookies</Link></div></footer>
      </main>
      <nav className="gb-bottom-nav" aria-label="Mobile navigation">{[{id:"casino" as View,label:"Casino",icon:Gamepad2},{id:"favorites" as View,label:"Saved",icon:Heart},{id:"bets" as View,label:"My bets",icon:History},{id:"rewards" as View,label:"Rewards",icon:Sparkles},{id:"account" as View,label:"Account",icon:UserRound}].map(item=><button key={item.id} className={view===item.id?"active":""} onClick={()=>navigate(item.id)}><item.icon size={21}/><span>{item.label}</span></button>)}</nav>
    </div>
    {searchOpen&&<div className="gb-search-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setSearchOpen(false)}}><div className="gb-search-modal" role="dialog" aria-modal="true" aria-label="Search games"><div className="gb-search-field"><Search size={20}/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search Galaxy Originals…"/><button onClick={()=>setSearchOpen(false)} aria-label="Close search"><X size={19}/></button></div><div className="gb-search-list">{filtered.map(g=><button key={g.id} onClick={()=>chooseGame(g.id)}><span className={`gb-search-icon ${g.color}`}><g.icon size={19}/></span><span><strong>{g.name}</strong><small>{g.category} · {g.line}</small></span></button>)}{filtered.length===0&&<p>No games found.</p>}</div></div></div>}
    {notice&&<div className="gb-toast" role="status"><Sparkles size={17}/>{notice}<button onClick={()=>setNotice("")} aria-label="Dismiss"><X size={15}/></button></div>}
  </div>;
}

type OptionProps={game:GameId;target:number;setTarget:(v:number)=>void;mode:"under"|"over";setMode:(v:"under"|"over")=>void;pick:string;setPick:(v:string)=>void;risk:string;setRisk:(v:string)=>void;rows:number;setRows:(v:number)=>void;mines:number;setMines:(v:number)=>void;difficulty:string;setDifficulty:(v:string)=>void;numbers:number[];setNumbers:(v:number[])=>void;disabled:boolean};
function GameOptions(p:OptionProps) {
  const choices=(values:string[],value:string,set:(v:string)=>void)=><div className="gb-choice-row">{values.map(v=><button key={v} disabled={p.disabled} className={value===v?"active":""} onClick={()=>set(v)}>{v}</button>)}</div>;
  if(p.game==="dice") return <><div className="gb-option-heading"><span>Win chance</span><strong>{p.mode==="under"?p.target:100-p.target}%</strong></div><Slider value={[p.target]} onValueChange={v=>p.setTarget(v[0])} min={2} max={98} step={1} disabled={p.disabled} aria-label="Dice target"/><div className="gb-slider-scale"><span>2%</span><span>50%</span><span>98%</span></div><label className="gb-label">Roll</label>{choices(["under","over"],p.mode,v=>p.setMode(v as "under"|"over"))}<p className="gb-option-hint">Target: {p.target.toFixed(2)} · Multiplier: {(0.99/(p.mode==="under"?p.target/100:1-p.target/100)).toFixed(2)}×</p></>;
  if(p.game==="limbo"||p.game==="crash") return <><label className="gb-label" htmlFor="target">{p.game==="crash"?"Auto cashout target":"Target multiplier"}</label><div className="gb-amount"><input id="target" type="number" min="1.1" max="100" step="0.1" value={p.target} onChange={e=>p.setTarget(Number(e.target.value))}/><span>×</span></div><p className="gb-option-hint">Target from 1.10× to 100×. {p.game==="crash"?"Solo instant round.":""}</p></>;
  if(p.game==="coinflip") return <><label className="gb-label">Choose a side</label>{choices(["Galaxy","Nova"],p.pick,p.setPick)}</>;
  if(p.game==="roulette") return <><label className="gb-label">Choose a color</label>{choices(["red","black","green"],p.pick,p.setPick)}</>;
  if(p.game==="baccarat") return <><label className="gb-label">Your prediction</label>{choices(["player","banker","tie"],p.pick,p.setPick)}</>;
  if(p.game==="plinko") return <><label className="gb-label">Rows</label><div className="gb-choice-row">{[8,10,12,14,16].map(n=><button key={n} className={p.rows===n?"active":""} disabled={p.disabled} onClick={()=>p.setRows(n)}>{n}</button>)}</div><label className="gb-label">Risk</label>{choices(["low","medium","high"],p.risk,p.setRisk)}</>;
  if(p.game==="mines") return <><label className="gb-label" htmlFor="mines">Supernovas</label><div className="gb-amount"><input id="mines" type="number" min="1" max="24" step="1" value={p.mines} disabled={p.disabled} onChange={e=>p.setMines(Number(e.target.value))}/><span>/ 25</span></div></>;
  if(p.game==="towers"||p.game==="chicken") return <><label className="gb-label">Difficulty</label>{choices(p.game==="towers"?["easy","medium","hard","expert"]:["easy","medium","hard","insane"],p.difficulty,p.setDifficulty)}</>;
  if(p.game==="keno") return <><label className="gb-label">Pick five numbers</label><div className="gb-keno-choices">{Array.from({length:40},(_,i)=>i+1).map(n=><button key={n} className={p.numbers.includes(n)?"active":""} onClick={()=>p.setNumbers(p.numbers.includes(n)?p.numbers.filter(x=>x!==n):p.numbers.length<5?[...p.numbers,n]:p.numbers)}>{n}</button>)}</div><p className="gb-option-hint">{p.numbers.length}/5 selected · 10 numbers drawn</p></>;
  if(p.game==="blackjack") return <p className="gb-option-hint">Dealer stands on 17. Natural blackjack pays 3:2. Hit or stand after the deal.</p>;
  if(p.game==="poker") return <p className="gb-option-hint">Deal five cards. Hold the cards you want, then draw once.</p>;
  if(p.game==="hilo") return <p className="gb-option-hint">Predict higher, lower, or same. Cash out after a correct prediction.</p>;
  return <p className="gb-option-hint">Outcomes are generated and recorded on the server.</p>;
}

type BoardProps={game:Game;latest:Bet|null;session:Session|null;busy:boolean;move:(action:string,pick?:unknown)=>void;holds:number[];setHolds:(v:number[])=>void};
function GameBoard({game,latest,session,busy,move,holds,setHolds}:BoardProps) {
  const outcome=latest?.outcome;
  const playing=session?.state==="ACTIVE";
  if(game.id==="dice") return <div className="gb-board gb-dice-board"><div className="gb-board-kicker">THE RESULT</div><div className={`gb-dice-number ${outcome?(outcome.won?"win":"loss"):""}`}>{outcome?Number(outcome.roll).toFixed(2):"— — . — —"}</div><div className="gb-dice-track"><span style={{left:`${outcome?Number(outcome.roll):50}%`}}/></div><div className="gb-dice-marks"><span>0.00</span><span>25.00</span><span>50.00</span><span>75.00</span><span>100.00</span></div><div className="gb-board-status">{outcome?(outcome.won?"WINNING ROLL":"BETTER LUCK NEXT ROLL"):"Set your odds and roll"}</div></div>;
  if(game.id==="mines") return <div className="gb-board gb-mines-board"><div className="gb-board-kicker">ASTEROID FIELD · {session?`${session.step} REVEALED`:"25 TILES"}</div><div className="gb-mines-grid">{Array.from({length:25},(_,i)=>{const opened=(session?.revealed as number[]|undefined)?.includes(i);const mine=(session?.mines as number[]|undefined)?.includes(i);return <button key={i} className={`${opened?"opened":""} ${mine?"mine":""}`} disabled={!playing||opened||busy} onClick={()=>move("select",i)} aria-label={`Tile ${i+1}${opened?" revealed":""}`}>{mine?<Zap size={20}/>:opened?<Gem size={21}/>:<Star size={13}/>}</button>;})}</div><div className="gb-board-status">{playing?<><strong>{Number(session.multiplier).toFixed(2)}×</strong><button onClick={()=>move("cashout")} disabled={busy}>Cash out</button></>:session?session.state==="LOST"?"A supernova was revealed":"Round complete":"Choose tiles to avoid supernovas"}</div></div>;
  if(game.id==="towers") return <div className="gb-board gb-towers-board"><div className="gb-board-kicker">ASCEND · LEVEL {session?Math.min(session.step+1,7):1} / 7</div><div className="gb-tower-grid">{Array.from({length:7},(_,r)=>{const row=6-r;return <div key={row} className={`gb-tower-row ${session&&row===session.step&&playing?"current":""}`}>{Array.from({length:Number(session?.cols||4)},(_,c)=>{const chosen=(session?.picks as number[]|undefined)?.[row]===c;const trap=(session?.rows as number[][]|undefined)?.[row]&&!((session?.rows as number[][])[row].includes(c));return <button key={c} disabled={!playing||row!==session?.step||busy} onClick={()=>move("select",c)} className={`${chosen?"chosen":""} ${trap?"trap":""}`} aria-label={`Level ${row+1} tile ${c+1}`}><Star size={15}/></button>})}</div>})}</div><div className="gb-board-status">{playing?<><strong>{Number(session.multiplier).toFixed(2)}×</strong>{session.step>0&&<button disabled={busy} onClick={()=>move("cashout")}>Cash out</button>}</>:session?session.state==="LOST"?"The tower collapsed":"Ascent complete":"Start, then choose a tile on each level"}</div></div>;
  if(game.id==="chicken") return <div className="gb-board gb-chicken-board"><div className="gb-board-kicker">CROSS THE LANES</div><div className="gb-road">{Array.from({length:8},(_,i)=><div key={i} className={`${session&&i<session.step?(session.lanes as boolean[]|undefined)?.[i]?"crossed":"danger":""}`}><span>0{i+1}</span><span>{session&&i<session.step?(session.lanes as boolean[]|undefined)?.[i]?"✦":"✕":"· · · · ·"}</span></div>)}</div><div className="gb-board-status">{playing?<><strong>{Number(session.multiplier).toFixed(2)}×</strong><button disabled={busy} onClick={()=>move("step")}>Next step</button>{session.step>0&&<button disabled={busy} onClick={()=>move("cashout")}>Cash out</button>}</>:session?session.state==="LOST"?"Hazard hit":"Road crossed":"Advance one lane at a time"}</div></div>;
  if(game.id==="hilo") return <div className="gb-board gb-card-board"><div className="gb-board-kicker">PREDICT THE NEXT CARD</div><div className="gb-card-hand"><div className="gb-playing-card"><span>{card(session?.current).slice(0,-1)}</span><strong>{card(session?.current)}</strong><span>{card(session?.current).slice(-1)}</span></div><span className="gb-card-vs">→</span><div className="gb-playing-card hidden-card">?</div></div><div className="gb-board-status">{playing?<><button disabled={busy} onClick={()=>move("guess","higher")}>Higher</button><button disabled={busy} onClick={()=>move("guess","same")}>Same</button><button disabled={busy} onClick={()=>move("guess","lower")}>Lower</button>{session.step>0&&<button disabled={busy} onClick={()=>move("cashout")}>Cash out {Number(session.multiplier).toFixed(2)}×</button>}</>:session?"Round complete":"Predict the next card"}</div></div>;
  if(game.id==="blackjack") return <div className="gb-board gb-card-board"><div className="gb-board-kicker">DEALER {session?.dealerTotal!==undefined?`· ${session.dealerTotal}`:""}</div><div className="gb-mini-hand">{(session?.dealer as (number|null)[]|undefined)?.map((n,i)=><span key={i} className={n===null?"face-down":""}>{card(n)}</span>)??<span className="face-down">?</span>}</div><div className="gb-table-line"/><div className="gb-board-kicker">YOUR HAND {session?.playerTotal!==undefined?`· ${session.playerTotal}`:""}</div><div className="gb-mini-hand">{(session?.player as number[]|undefined)?.map((n,i)=><span key={i}>{card(n)}</span>)??<span className="face-down">?</span>}</div><div className="gb-board-status">{playing?<><button disabled={busy} onClick={()=>move("hit")}>Hit</button><button disabled={busy} onClick={()=>move("stand")}>Stand</button></>:session?session.state==="WON"?"Hand won or pushed":"Dealer wins":"Deal a hand to begin"}</div></div>;
  if(game.id==="poker") return <div className="gb-board gb-card-board"><div className="gb-board-kicker">VIDEO POKER · HOLD & DRAW</div><div className="gb-poker-hand">{(session?.hand as number[]|undefined)?.map((n,i)=><button key={i} disabled={!playing||busy} className={`gb-playing-card ${holds.includes(i)?"held":""}`} onClick={()=>setHolds(holds.includes(i)?holds.filter(x=>x!==i):[...holds,i])}><strong>{card(n)}</strong><span>{holds.includes(i)?"HELD":"HOLD"}</span></button>)??Array.from({length:5},(_,i)=><div key={i} className="gb-playing-card hidden-card">?</div>)}</div><div className="gb-board-status">{playing?<button disabled={busy} onClick={()=>move("draw",holds)}>Draw cards</button>:session?String(session.rankName??"Hand complete"):"Deal cards to begin"}</div></div>;
  if(game.id==="plinko") return <div className="gb-board gb-plinko-board"><div className="gb-board-kicker">COSMIC GRAVITY BOARD</div><div className="gb-pegs">{Array.from({length:10},(_,row)=><div key={row}>{Array.from({length:row+3},(_,col)=><span key={col} className={outcome&&row===9&&col===Number(outcome.slot)?"landing":""}/>)}</div>)}</div><div className="gb-plinko-slots">{["×","×","×","×","×","×","×","×","×","×","×"].map((x,i)=><span key={i} className={outcome&&i===Number(outcome.slot)?"lit":""}>{x}</span>)}</div><div className="gb-board-status">{outcome?`Landed in slot ${Number(outcome.slot)+1} · ${Number(outcome.multiplier).toFixed(2)}×`:"Drop a ball through the board"}</div></div>;
  if(game.id==="coinflip") return <div className="gb-board gb-simple-board"><div className="gb-board-kicker">GALAXY OR NOVA</div><div className={`gb-coin ${outcome?"flipped":""}`}><Orbit size={63} strokeWidth={1}/><strong>{outcome?String(outcome.result):"G / N"}</strong></div><div className="gb-board-status">{outcome?outcome.won?"You called it":"The other side landed":"Pick your side"}</div></div>;
  if(game.id==="wheel") return <div className="gb-board gb-simple-board"><div className="gb-board-kicker">THE ORBIT WHEEL</div><div className="gb-wheel"><div>{outcome?`${Number(outcome.multiplier).toFixed(2)}×`:"SPIN"}</div></div><div className="gb-board-status">{outcome?`Segment ${Number(outcome.segment)+1} of 10`:"Spin for a multiplier"}</div></div>;
  if(game.id==="keno") return <div className="gb-board gb-keno-board"><div className="gb-board-kicker">TEN NUMBERS DRAWN</div><div className="gb-keno-results">{Array.from({length:10},(_,i)=><span key={i} className={outcome&&(outcome.selected as number[]).includes((outcome.draw as number[])[i])?"matched":""}>{outcome?(outcome.draw as number[])[i]:"•"}</span>)}</div><div className="gb-board-status">{outcome?`${outcome.matches} matches · ${Number(outcome.multiplier).toFixed(2)}×`:"Choose five numbers to play"}</div></div>;
  if(game.id==="roulette") return <div className="gb-board gb-simple-board"><div className="gb-board-kicker">ROULETTE · 0–36</div><div className={`gb-roulette-ball ${outcome?String(outcome.color):""}`}>{outcome?String(outcome.number):"?"}</div><div className="gb-board-status">{outcome?`${String(outcome.color).toUpperCase()} · ${outcome.won?"WIN":"LOSS"}`:"Pick red, black, or green"}</div></div>;
  if(game.id==="baccarat") return <div className="gb-board gb-card-board"><div className="gb-board-kicker">PLAYER VS BANKER</div><div className="gb-baccarat"><div><span>PLAYER · {outcome?String(outcome.playerTotal):"—"}</span><div className="gb-mini-hand">{(outcome?.player as number[]|undefined)?.map((n,i)=><span key={i}>{n}</span>)??<span className="face-down">?</span>}</div></div><div><span>BANKER · {outcome?String(outcome.bankerTotal):"—"}</span><div className="gb-mini-hand">{(outcome?.banker as number[]|undefined)?.map((n,i)=><span key={i}>{n}</span>)??<span className="face-down">?</span>}</div></div></div><div className="gb-board-status">{outcome?`${String(outcome.result).toUpperCase()} WINS`:"Choose a side"}</div></div>;
  return <div className="gb-board gb-simple-board"><div className="gb-board-kicker">{game.name.toUpperCase()}</div><div className="gb-big-multiplier">{outcome?`${Number(outcome.result).toFixed(2)}×`:"1.00×"}</div><div className="gb-orbit-line"/><div className="gb-board-status">{outcome?outcome.won?"Target reached":"Result below target":game.id==="crash"?"Set an auto cashout target for this solo round":"Set a target multiplier"}</div></div>;
}
